apiVersion: batch/v1
kind: Job
metadata:
  name: write-table-postgrse
spec:
  template:
    spec:
      containers:
      - name: pi
        image: <you image name> erc image url
      restartPolicy: Never
  backoffLimit: 1
