apiVersion: batch/v1
kind: Job
metadata:
  name:

spec:
  template:
    spec:
      containers:
      - name: pi
        image: 723653791098.dkr.ecr.us-east-1.amazonaws.com/bmc-docker
      restartPolicy: Never
  backoffLimit: 1
