apiVersion: batch/v1
kind: Job
metadata:
  name: print-tables-postgrse
spec:
  template:
    spec:
      containers:
      - name: pi
        image: 723653791098.dkr.ecr.us-east-1.amazonaws.com/job4
      restartPolicy: Never
  backoffLimit: 1
