apiVersion: v1
kind: PersistentVolume
metadata:
name: postgresql-pv
labels:
type: local
   spec:
      containers:
      - name: pi
        image: 723653791098.dkr.ecr.us-east-1.amazonaws.com/job5
      restartPolicy: Never
  backoffLimit: 1